#!/usr/bin/env python3
"""
Mundi Engine - Lua 바인딩 자동 생성 도구

UPROPERTY와 UFUNCTION 매크로를 파싱하여
.generated.cpp 파일을 자동 생성합니다.

사용법:
    python generate.py --source-dir <소스 디렉토리> --output-dir <출력 디렉토리>
"""

import argparse
import sys
from pathlib import Path
from parser import HeaderParser
from property_generator import PropertyGenerator
from lua_generator import LuaBindingGenerator


GENERATED_FILE_TEMPLATE = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "{header_include}"
#include "Core/Object/ObjectMacros.h"
#include "Engine/Scripting/LuaBindHelpers.h"

// ===== Property Reflection =====
{property_code}

// ===== Lua Binding =====
{lua_code}
"""


def generate_code_for_class(class_info, prop_gen, lua_gen):
    """클래스에 대한 완전한 .generated.cpp 파일 생성"""
    # 헤더 파일 상대 경로 계산
    header_include = class_info.header_file.name

    # 프로퍼티 코드 생성
    property_code = prop_gen.generate(class_info)

    # Lua 바인딩 코드 생성
    lua_code = lua_gen.generate(class_info)

    # 최종 파일 내용
    return GENERATED_FILE_TEMPLATE.format(
        header_include=header_include,
        property_code=property_code,
        lua_code=lua_code
    )


def main():
    parser = argparse.ArgumentParser(
        description='Mundi Engine Lua Binding Auto-Generator'
    )
    parser.add_argument(
        '--source-dir',
        type=Path,
        required=True,
        help='소스 디렉토리 경로 (예: Source/Runtime)'
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        required=True,
        help='생성된 파일 출력 디렉토리 (예: Build/Generated)'
    )

    args = parser.parse_args()

    # 디렉토리 존재 확인
    if not args.source_dir.exists():
        print(f"❌ Error: Source directory not found: {args.source_dir}")
        sys.exit(1)

    # 출력 디렉토리 생성
    args.output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("🔨 Mundi Engine - Code Generator")
    print("=" * 60)
    print(f"📁 Source: {args.source_dir}")
    print(f"📁 Output: {args.output_dir}")
    print()

    # 파서 초기화
    header_parser = HeaderParser()
    prop_gen = PropertyGenerator()
    lua_gen = LuaBindingGenerator()

    # 헤더 파일 스캔
    print("🔍 Scanning for reflection classes...")
    classes = header_parser.find_reflection_classes(args.source_dir)

    if not classes:
        print("⚠️  No classes with GENERATED_REFLECTION_BODY() found.")
        return

    print(f"\n✅ Found {len(classes)} reflection class(es)\n")

    # 각 클래스에 대해 .generated.cpp 생성
    generated_files = []
    for class_info in classes:
        output_file = args.output_dir / f"{class_info.name}.generated.cpp"

        # 코드 생성
        generated_code = generate_code_for_class(class_info, prop_gen, lua_gen)

        # 파일 쓰기
        output_file.write_text(generated_code, encoding='utf-8')
        generated_files.append(output_file)

        print(f"✓ Generated: {output_file.name}")
        print(f"  ├─ Properties: {len(class_info.properties)}")
        print(f"  └─ Functions:  {len([f for f in class_info.functions if f.metadata.get('lua_bind')])}")

    print()
    print("=" * 60)
    print(f"✅ Code generation complete! ({len(generated_files)} files)")
    print("=" * 60)


if __name__ == '__main__':
    main()
