#!/usr/bin/env python3
"""
Mundi Engine - Lua 바인딩 자동 생성 도구

UPROPERTY와 UFUNCTION 매크로를 파싱하여
.generated.cpp 파일을 자동 생성합니다.

사용법:
    python generate.py --source-dir <소스 디렉토리> --output-dir <출력 디렉토리>
"""

import argparse
import sys
from pathlib import Path
from parser import HeaderParser
from property_generator import PropertyGenerator
from lua_generator import LuaBindingGenerator


GENERATED_HEADER_TEMPLATE = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#pragma once

// Macro expansion for GENERATED_REFLECTION_BODY()
// This file must be included BEFORE the class definition
#define CURRENT_CLASS_GENERATED_BODY \\
public: \\
    /* DECLARE_CLASS functionality */ \\
    using Super = {parent_class}; \\
    using ThisClass_t = {class_name}; \\
    static UClass* StaticClass() \\
    {{ \\
        static UClass Cls{{ "{class_name}", {parent_class}::StaticClass(), sizeof({class_name}) }}; \\
        static bool bRegistered = []() {{ \\
            UClass::SignUpClass(&Cls); \\
            return true; \\
        }}(); \\
        return &Cls; \\
    }} \\
    virtual UClass* GetClass() const override {{ return {class_name}::StaticClass(); }} \\
    \\
    /* DECLARE_DUPLICATE functionality */ \\
    {class_name}(const {class_name}&) = default; \\
    {class_name}* Duplicate() const override \\
    {{ \\
        {class_name}* NewObject = ObjectFactory::DuplicateObject<{class_name}>(this); \\
        NewObject->DuplicateSubObjects(); \\
        NewObject->PostDuplicate(); \\
        return NewObject; \\
    }} \\
    \\
    /* Reflection registration */ \\
private: \\
    static void StaticRegisterProperties(); \\
    static const bool bPropertiesRegistered; \\
public:
"""

GENERATED_CPP_TEMPLATE = """// Auto-generated file - DO NOT EDIT!
// Generated by Tools/CodeGenerator/generate.py

#include "pch.h"
#include "{header_include}"
#include "Source/Runtime/Core/Object/ObjectMacros.h"
#include "Source/Runtime/Engine/Scripting/LuaBindHelpers.h"

// ===== Class Factory Registration (IMPLEMENT_CLASS) =====
{implement_class_code}

// ===== Property Reflection =====
{property_code}

// ===== Lua Binding =====
{lua_code}
"""


def generate_header_file(class_info):
    """.generated.h 파일 생성"""
    return GENERATED_HEADER_TEMPLATE.format(
        class_name=class_info.name,
        parent_class=class_info.parent
    )


def generate_implement_class(class_info):
    """IMPLEMENT_CLASS 매크로 확장 코드 생성"""
    class_name = class_info.name
    return f"""
// IMPLEMENT_CLASS({class_name}) expansion
namespace {{
    struct {class_name}FactoryRegister
    {{
        {class_name}FactoryRegister()
        {{
            ObjectFactory::RegisterClassType(
                {class_name}::StaticClass(),
                []() -> UObject* {{ return new {class_name}(); }}
            );
        }}
    }};
    static {class_name}FactoryRegister GRegister_{class_name};
    static bool bIsRegistered_{class_name} = [](){{ {class_name}::StaticClass(); return true; }}();
}}

// Static member initialization for reflection registration
const bool {class_name}::bPropertiesRegistered = []() {{
    {class_name}::StaticRegisterProperties();
    return true;
}}();
"""


def generate_cpp_file(class_info, prop_gen, lua_gen):
    """.generated.cpp 파일 생성"""
    # 헤더 파일 상대 경로 계산
    header_include = class_info.header_file.name

    # IMPLEMENT_CLASS 코드 생성
    implement_class_code = generate_implement_class(class_info)

    # 프로퍼티 코드 생성
    property_code = prop_gen.generate(class_info)

    # Lua 바인딩 코드 생성
    lua_code = lua_gen.generate(class_info)

    # 최종 파일 내용
    return GENERATED_CPP_TEMPLATE.format(
        header_include=header_include,
        implement_class_code=implement_class_code,
        property_code=property_code,
        lua_code=lua_code
    )


def main():
    parser = argparse.ArgumentParser(
        description='Mundi Engine Lua Binding Auto-Generator'
    )
    parser.add_argument(
        '--source-dir',
        type=Path,
        required=True,
        help='소스 디렉토리 경로 (예: Source/Runtime)'
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        required=True,
        help='생성된 파일 출력 디렉토리 (예: Build/Generated)'
    )

    args = parser.parse_args()

    # 디렉토리 존재 확인
    if not args.source_dir.exists():
        print(f"❌ Error: Source directory not found: {args.source_dir}")
        sys.exit(1)

    # 출력 디렉토리 생성
    args.output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("🔨 Mundi Engine - Code Generator")
    print("=" * 60)
    print(f"📁 Source: {args.source_dir}")
    print(f"📁 Output: {args.output_dir}")
    print()

    # 파서 초기화
    header_parser = HeaderParser()
    prop_gen = PropertyGenerator()
    lua_gen = LuaBindingGenerator()

    # 헤더 파일 스캔
    print("🔍 Scanning for reflection classes...")
    classes = header_parser.find_reflection_classes(args.source_dir)

    if not classes:
        print("⚠️  No classes with GENERATED_REFLECTION_BODY() found.")
        return

    print(f"\n✅ Found {len(classes)} reflection class(es)\n")

    # 각 클래스에 대해 .generated.h와 .generated.cpp 생성
    generated_files = []
    for class_info in classes:
        # .generated.h 파일 생성
        header_output = args.output_dir / f"{class_info.name}.generated.h"
        header_code = generate_header_file(class_info)
        header_output.write_text(header_code, encoding='utf-8')
        generated_files.append(header_output)

        # .generated.cpp 파일 생성
        cpp_output = args.output_dir / f"{class_info.name}.generated.cpp"
        cpp_code = generate_cpp_file(class_info, prop_gen, lua_gen)
        cpp_output.write_text(cpp_code, encoding='utf-8')
        generated_files.append(cpp_output)

        print(f"✓ Generated: {class_info.name}")
        print(f"  ├─ {header_output.name}")
        print(f"  ├─ {cpp_output.name}")
        print(f"  ├─ Properties: {len(class_info.properties)}")
        print(f"  └─ Functions:  {len([f for f in class_info.functions if f.metadata.get('lua_bind')])}")

    print()
    print("=" * 60)
    print(f"✅ Code generation complete! ({len(generated_files)} files)")
    print("=" * 60)


if __name__ == '__main__':
    main()
